language: c
os: linux
sudo: required
dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get -y install autotools-dev audacious-dev libglib2.0-dev
install:
  - cd ~
  - mkdir sdl2install
  - export SDL2DIR="`pwd`/sdl2install"
  - wget https://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar xzf SDL2-2.0.3.tar.gz
  - cd SDL2-2.0.3
  - ./autogen.sh --prefix=$SDL2DIR
  - make
  - make install
compiler:
  - clang
  - gcc
notifications:
  email:
  - dprotti@gmail.com