language: c
os: linux
sudo: required
dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get -y install audacious-dev libsdl2-2.0-0 libglib2.0-dev
script: 
  - ./autogen.sh
  - make
compiler:
  - clang
  - gcc
notifications:
  email:
  - dprotti@gmail.com